[workspace]
resolver = "3"
members = [
    "A_Production-Grade_Concurrent_In-Memory_Key-Value_Store_",
    "add_digits",
    "anargam",
    "chat_server",
    "contains_duplicate",
    "Contains_Duplicate_2",
    "Countr_Currency",
    "crypto_watchlist",
    "Happy_number",
    "Implement_Stack_Using_Queues",
    "Invert_Binary_Tree",
    "is_bad",
    "Isomorphic_Strings",
    "missing_numbers",
    "Move_Zeros",
    "Number_of_1_Bits",
    "power_of_two",
    "queue_using_stack",
    "radis_caching",
    "Reverse_Bits",
    "rust_rest_api",
    "rust-api-tutorial",
    "summary_ranges",
    "Task_Api",
    "ugly_number",
    "weather_api",
    "rate_limiter",
    "word_pattarn"
, "Range_sum", "power_of_three"]
