services:
  redis:
    image: redis:7
    ports:
      - "6380:6379"
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: productsdb
    ports:
      - "5435:5432" 